-- LiMATO Box Challenge v0.5.0 — Supabase setup
-- Run this ONCE in Supabase > SQL Editor.
-- Then enable Anonymous Sign-Ins in Authentication > Sign In / Providers.

create table if not exists public.lbc_rooms (
  code text primary key,
  host_id uuid not null,
  max_number integer not null check (max_number in (9,12,15,18)),
  rounds integer not null check (rounds in (3,5,7)),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.lbc_room_players (
  id bigint generated by default as identity primary key,
  room_code text not null references public.lbc_rooms(code) on delete cascade,
  owner_id uuid not null,
  nickname text not null check (char_length(nickname) between 1 and 24),
  progress_round integer not null default 0,
  partial_score integer not null default 0,
  total_score integer,
  finished boolean not null default false,
  started_at timestamptz,
  finished_at timestamptz,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_code, owner_id)
);

create table if not exists public.lbc_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  event_type text not null check (event_type in ('visit','start_match','finish_match')),
  source text not null default 'direct',
  box_number integer,
  rounds integer,
  total_score integer,
  language text,
  room_code text,
  created_at timestamptz not null default now()
);

create table if not exists public.lbc_ratings (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  rating integer not null check (rating between 1 and 5),
  language text,
  source text not null default 'direct',
  created_at timestamptz not null default now()
);

create index if not exists lbc_room_players_room_idx on public.lbc_room_players(room_code);
create index if not exists lbc_events_created_idx on public.lbc_events(created_at);
create index if not exists lbc_events_owner_idx on public.lbc_events(owner_id);
create index if not exists lbc_events_type_idx on public.lbc_events(event_type);
create index if not exists lbc_ratings_created_idx on public.lbc_ratings(created_at);

alter table public.lbc_rooms enable row level security;
alter table public.lbc_room_players enable row level security;
alter table public.lbc_events enable row level security;
alter table public.lbc_ratings enable row level security;

-- Minimal grants for anonymous-authenticated players.
grant select, insert, update on public.lbc_rooms to authenticated;
grant select, insert, update on public.lbc_room_players to authenticated;
grant insert on public.lbc_events to authenticated;
grant insert on public.lbc_ratings to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- RLS policies. Drop first so this script can be safely rerun.
drop policy if exists "rooms_read" on public.lbc_rooms;
drop policy if exists "rooms_insert_host" on public.lbc_rooms;
drop policy if exists "rooms_update_host" on public.lbc_rooms;
drop policy if exists "players_read" on public.lbc_room_players;
drop policy if exists "players_insert_self" on public.lbc_room_players;
drop policy if exists "players_update_self" on public.lbc_room_players;
drop policy if exists "events_insert_self" on public.lbc_events;
drop policy if exists "ratings_insert_self" on public.lbc_ratings;

create policy "rooms_read" on public.lbc_rooms for select to authenticated using (true);
create policy "rooms_insert_host" on public.lbc_rooms for insert to authenticated with check (host_id = auth.uid());
create policy "rooms_update_host" on public.lbc_rooms for update to authenticated using (host_id = auth.uid()) with check (host_id = auth.uid());

create policy "players_read" on public.lbc_room_players for select to authenticated using (true);
create policy "players_insert_self" on public.lbc_room_players for insert to authenticated with check (owner_id = auth.uid());
create policy "players_update_self" on public.lbc_room_players for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());

create policy "events_insert_self" on public.lbc_events for insert to authenticated with check (owner_id = auth.uid());
create policy "ratings_insert_self" on public.lbc_ratings for insert to authenticated with check (owner_id = auth.uid());

-- Keep updated_at fresh for online leaderboard rows.
create or replace function public.lbc_set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lbc_room_players_updated_at on public.lbc_room_players;
create trigger lbc_room_players_updated_at
before update on public.lbc_room_players
for each row execute function public.lbc_set_updated_at();

-- Realtime for the live room leaderboard.
do $$
begin
  alter publication supabase_realtime add table public.lbc_room_players;
exception
  when duplicate_object then null;
end $$;

-- Private owner-only dashboard views. They are NOT exposed to game clients.
create schema if not exists private;

create or replace view private.lbc_stats_30d as
with visits as (
  select owner_id, count(distinct created_at::date) as visit_days
  from public.lbc_events
  where event_type='visit' and created_at >= now() - interval '30 days'
  group by owner_id
), starters as (
  select distinct owner_id
  from public.lbc_events
  where event_type='start_match' and created_at >= now() - interval '30 days'
)
select
  (select count(*) from visits) as visitors_30d,
  (select count(*) from starters) as players_started_30d,
  (select count(*) from visits where visit_days >= 2) as returning_players_30d,
  (select count(*) from public.lbc_events where event_type='start_match' and created_at >= now() - interval '30 days') as matches_started_30d,
  (select count(*) from public.lbc_events where event_type='finish_match' and created_at >= now() - interval '30 days') as matches_finished_30d,
  (select round(avg(rating)::numeric,2) from public.lbc_ratings where created_at >= now() - interval '30 days') as average_rating_30d,
  (select count(*) from public.lbc_ratings where created_at >= now() - interval '30 days') as ratings_30d;

create or replace view private.lbc_sources_30d as
select
  source,
  count(*) filter (where event_type='visit') as visits,
  count(distinct owner_id) filter (where event_type='visit') as unique_visitors,
  count(distinct owner_id) filter (where event_type='start_match') as players_started,
  count(*) filter (where event_type='start_match') as matches_started,
  count(*) filter (where event_type='finish_match') as matches_finished
from public.lbc_events
where created_at >= now() - interval '30 days'
group by source
order by players_started desc, unique_visitors desc;

revoke all on schema private from anon, authenticated;
revoke all on private.lbc_stats_30d from anon, authenticated;
revoke all on private.lbc_sources_30d from anon, authenticated;

-- Owner dashboard queries (run in SQL Editor whenever you want):
-- select * from private.lbc_stats_30d;
-- select * from private.lbc_sources_30d;
-- select rating, count(*) from public.lbc_ratings group by rating order by rating desc;
