-- LiMATO Box Challenge v0.6.0 — Arena migration
-- RUN ONCE in Supabase > SQL Editor.
-- This migration ADDS v0.6.0 tables/functions. It does NOT delete v0.5.0 rooms, stats or ratings.

create extension if not exists pgcrypto;

-- 1) Player profile for the v0.6 identity.
create table if not exists public.lbc_profiles (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(trim(nickname)) between 2 and 24),
  completed_games integer not null default 0 check (completed_games >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2) Automatic Arena matchmaking queue.
create table if not exists public.lbc_arena_queue (
  owner_id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(trim(nickname)) between 2 and 24),
  max_number integer not null check (max_number in (9,12,15,18)),
  rounds integer not null check (rounds in (3,5,7)),
  player_count integer not null check (player_count between 2 and 6),
  persona text not null default 'friend' check (persona in ('friend','professor','provoker','comic','silent')),
  status text not null default 'queued' check (status in ('queued','matched','cancelled')),
  match_id uuid,
  joined_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

-- 3) Arena matches. Entry fields are placeholders only; v0.6.0 runs FREE.
create table if not exists public.lbc_arena_matches (
  id uuid primary key default gen_random_uuid(),
  max_number integer not null check (max_number in (9,12,15,18)),
  rounds integer not null check (rounds in (3,5,7)),
  player_count integer not null check (player_count between 2 and 6),
  status text not null default 'playing' check (status in ('waiting','playing','finished','abandoned')),
  current_seat integer not null default 1,
  current_round integer not null default 1,
  turn_seconds integer not null check (turn_seconds between 10 and 120),
  turn_started_at timestamptz,
  entry_currency text not null default 'free' check (entry_currency in ('free','eur','pi')),
  entry_amount numeric(18,8) not null default 0 check (entry_amount >= 0),
  created_at timestamptz not null default now(),
  finished_at timestamptz
);

alter table public.lbc_arena_queue
  drop constraint if exists lbc_arena_queue_match_fk;
alter table public.lbc_arena_queue
  add constraint lbc_arena_queue_match_fk foreign key (match_id)
  references public.lbc_arena_matches(id) on delete set null;

-- 4) Players inside one Arena match.
create table if not exists public.lbc_arena_players (
  match_id uuid not null references public.lbc_arena_matches(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(trim(nickname)) between 2 and 24),
  seat integer not null check (seat between 1 and 6),
  persona text not null default 'friend' check (persona in ('friend','professor','provoker','comic','silent')),
  round_scores integer[] not null default '{}',
  partial_score integer not null default 0,
  total_score integer,
  status text not null default 'playing' check (status in ('playing','finished','abandoned')),
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (match_id, owner_id),
  unique (match_id, seat)
);

-- 5) Live board snapshot watched by the other players.
create table if not exists public.lbc_arena_state (
  match_id uuid not null references public.lbc_arena_matches(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  round_number integer not null default 1,
  open_numbers integer[] not null default '{}',
  dice_values integer[] not null default '{}',
  target integer,
  round_score integer not null default 0,
  total_score integer not null default 0,
  message text,
  updated_at timestamptz not null default now(),
  primary key (match_id, owner_id)
);

-- 6) Community Voice. All user submissions start as PENDING.
create table if not exists public.lbc_community_comments (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(trim(nickname)) between 2 and 24),
  language text not null default 'sl',
  persona text not null check (persona in ('friend','professor','provoker','comic')),
  body text not null check (char_length(body) between 3 and 75),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

-- We do NOT store rejected raw abuse here — only the category/time.
create table if not exists public.lbc_moderation_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  created_at timestamptz not null default now()
);

-- 7) Tournament foundation. Hidden in UI for now.
create table if not exists public.lbc_tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  size integer not null check (size in (4,8,16,32,64,128)),
  max_number integer not null check (max_number in (9,12,15,18)),
  rounds integer not null check (rounds in (3,5,7)),
  status text not null default 'draft' check (status in ('draft','open','running','finished','cancelled')),
  entry_currency text not null default 'free' check (entry_currency in ('free','eur','pi')),
  entry_amount numeric(18,8) not null default 0 check (entry_amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.lbc_tournament_entries (
  tournament_id uuid not null references public.lbc_tournaments(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null,
  seed integer,
  status text not null default 'entered' check (status in ('entered','active','eliminated','winner','withdrawn')),
  created_at timestamptz not null default now(),
  primary key (tournament_id,owner_id)
);

create index if not exists lbc_arena_queue_match_idx on public.lbc_arena_queue(max_number,rounds,player_count,status,joined_at);
create index if not exists lbc_arena_players_match_idx on public.lbc_arena_players(match_id,seat);
create index if not exists lbc_arena_state_match_idx on public.lbc_arena_state(match_id,updated_at);
create index if not exists lbc_community_status_idx on public.lbc_community_comments(status,language,persona,created_at);

-- ---------- RLS ----------
alter table public.lbc_profiles enable row level security;
alter table public.lbc_arena_queue enable row level security;
alter table public.lbc_arena_matches enable row level security;
alter table public.lbc_arena_players enable row level security;
alter table public.lbc_arena_state enable row level security;
alter table public.lbc_community_comments enable row level security;
alter table public.lbc_moderation_events enable row level security;
alter table public.lbc_tournaments enable row level security;
alter table public.lbc_tournament_entries enable row level security;

grant select,insert,update on public.lbc_profiles to authenticated;
grant select,insert,update,delete on public.lbc_arena_queue to authenticated;
grant select on public.lbc_arena_matches to authenticated;
grant select,insert,update on public.lbc_arena_players to authenticated;
grant select,insert,update on public.lbc_arena_state to authenticated;
grant select,insert on public.lbc_community_comments to authenticated;
grant insert,select on public.lbc_moderation_events to authenticated;
grant select on public.lbc_tournaments to authenticated;
grant select,insert,update on public.lbc_tournament_entries to authenticated;
grant usage,select on all sequences in schema public to authenticated;

drop policy if exists profiles_self_select on public.lbc_profiles;
drop policy if exists profiles_self_insert on public.lbc_profiles;
drop policy if exists profiles_self_update on public.lbc_profiles;
create policy profiles_self_select on public.lbc_profiles for select to authenticated using (owner_id=auth.uid());
create policy profiles_self_insert on public.lbc_profiles for insert to authenticated with check (owner_id=auth.uid());
create policy profiles_self_update on public.lbc_profiles for update to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid());

drop policy if exists arena_queue_self_select on public.lbc_arena_queue;
drop policy if exists arena_queue_self_insert on public.lbc_arena_queue;
drop policy if exists arena_queue_self_update on public.lbc_arena_queue;
drop policy if exists arena_queue_self_delete on public.lbc_arena_queue;
create policy arena_queue_self_select on public.lbc_arena_queue for select to authenticated using (owner_id=auth.uid());
create policy arena_queue_self_insert on public.lbc_arena_queue for insert to authenticated with check (owner_id=auth.uid());
create policy arena_queue_self_update on public.lbc_arena_queue for update to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy arena_queue_self_delete on public.lbc_arena_queue for delete to authenticated using (owner_id=auth.uid());

-- Security-definer membership helper avoids recursive RLS policies.
create or replace function public.lbc_is_match_member(p_match_id uuid)
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select exists(
    select 1 from public.lbc_arena_players
    where match_id=p_match_id and owner_id=auth.uid()
  );
$$;
revoke all on function public.lbc_is_match_member(uuid) from public;
grant execute on function public.lbc_is_match_member(uuid) to authenticated;

drop policy if exists arena_matches_member_select on public.lbc_arena_matches;
create policy arena_matches_member_select on public.lbc_arena_matches for select to authenticated
using (public.lbc_is_match_member(id));

drop policy if exists arena_players_member_select on public.lbc_arena_players;
drop policy if exists arena_players_self_insert on public.lbc_arena_players;
drop policy if exists arena_players_self_update on public.lbc_arena_players;
create policy arena_players_member_select on public.lbc_arena_players for select to authenticated
using (public.lbc_is_match_member(match_id));
create policy arena_players_self_insert on public.lbc_arena_players for insert to authenticated
with check (owner_id=auth.uid());
create policy arena_players_self_update on public.lbc_arena_players for update to authenticated
using (owner_id=auth.uid()) with check (owner_id=auth.uid());

drop policy if exists arena_state_member_select on public.lbc_arena_state;
drop policy if exists arena_state_self_insert on public.lbc_arena_state;
drop policy if exists arena_state_self_update on public.lbc_arena_state;
create policy arena_state_member_select on public.lbc_arena_state for select to authenticated
using (public.lbc_is_match_member(match_id));
create policy arena_state_self_insert on public.lbc_arena_state for insert to authenticated
with check (owner_id=auth.uid() and public.lbc_is_match_member(match_id));
create policy arena_state_self_update on public.lbc_arena_state for update to authenticated
using (owner_id=auth.uid()) with check (owner_id=auth.uid() and public.lbc_is_match_member(match_id));

drop policy if exists community_approved_or_self on public.lbc_community_comments;
drop policy if exists community_self_insert on public.lbc_community_comments;
create policy community_approved_or_self on public.lbc_community_comments for select to authenticated
using (status='approved' or owner_id=auth.uid());
create policy community_self_insert on public.lbc_community_comments for insert to authenticated
with check (owner_id=auth.uid() and status='pending');

drop policy if exists moderation_self_select on public.lbc_moderation_events;
drop policy if exists moderation_self_insert on public.lbc_moderation_events;
create policy moderation_self_select on public.lbc_moderation_events for select to authenticated using (owner_id=auth.uid());
create policy moderation_self_insert on public.lbc_moderation_events for insert to authenticated with check (owner_id=auth.uid());

drop policy if exists tournaments_public_select on public.lbc_tournaments;
create policy tournaments_public_select on public.lbc_tournaments for select to authenticated using (status in ('open','running','finished'));

drop policy if exists tournament_entries_member_select on public.lbc_tournament_entries;
drop policy if exists tournament_entries_self_insert on public.lbc_tournament_entries;
drop policy if exists tournament_entries_self_update on public.lbc_tournament_entries;
create policy tournament_entries_member_select on public.lbc_tournament_entries for select to authenticated using (true);
create policy tournament_entries_self_insert on public.lbc_tournament_entries for insert to authenticated with check (owner_id=auth.uid());
create policy tournament_entries_self_update on public.lbc_tournament_entries for update to authenticated using (owner_id=auth.uid()) with check (owner_id=auth.uid());

-- ---------- Matchmaking RPC ----------
create or replace function public.lbc_arena_join_queue(
  p_nickname text,
  p_max_number integer,
  p_rounds integer,
  p_player_count integer,
  p_persona text
)
returns table(out_match_id uuid,out_status text,out_waiting integer)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  v_match uuid;
  v_ids uuid[];
  v_count integer:=0;
  v_turn integer;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  p_nickname:=trim(regexp_replace(coalesce(p_nickname,''),'\s+',' ','g'));
  if char_length(p_nickname)<2 or char_length(p_nickname)>24 then raise exception 'nickname_invalid'; end if;
  if p_max_number not in (9,12,15,18) then raise exception 'box_invalid'; end if;
  if p_rounds not in (3,5,7) then raise exception 'rounds_invalid'; end if;
  if p_player_count<2 or p_player_count>6 then raise exception 'player_count_invalid'; end if;
  if p_persona not in ('friend','professor','provoker','comic','silent') then p_persona:='friend'; end if;

  -- One lock per ruleset avoids two clients creating the same group at once.
  perform pg_advisory_xact_lock(hashtext(p_max_number::text||':'||p_rounds::text||':'||p_player_count::text));

  delete from public.lbc_arena_queue
  where status='queued' and last_seen < now()-interval '90 seconds';

  insert into public.lbc_arena_queue(owner_id,nickname,max_number,rounds,player_count,persona,status,match_id,joined_at,last_seen)
  values(v_uid,p_nickname,p_max_number,p_rounds,p_player_count,p_persona,'queued',null,now(),now())
  on conflict(owner_id) do update set
    nickname=excluded.nickname,max_number=excluded.max_number,rounds=excluded.rounds,
    player_count=excluded.player_count,persona=excluded.persona,status='queued',
    match_id=null,joined_at=now(),last_seen=now();

  select count(*) into v_count from public.lbc_arena_queue
  where status='queued' and max_number=p_max_number and rounds=p_rounds and player_count=p_player_count;

  if v_count>=p_player_count then
    select array_agg(owner_id) into v_ids
    from (
      select owner_id from public.lbc_arena_queue
      where status='queued' and max_number=p_max_number and rounds=p_rounds and player_count=p_player_count
      order by joined_at
      for update skip locked
      limit p_player_count
    ) s;

    if coalesce(cardinality(v_ids),0)>=p_player_count then
      v_turn:=case p_max_number when 9 then 20 when 12 then 25 when 15 then 30 else 45 end;
      insert into public.lbc_arena_matches(max_number,rounds,player_count,status,current_seat,current_round,turn_seconds,turn_started_at)
      values(p_max_number,p_rounds,p_player_count,'playing',1,1,v_turn,now())
      returning id into v_match;

      update public.lbc_arena_queue set status='matched',match_id=v_match,last_seen=now()
      where owner_id=any(v_ids);

      insert into public.lbc_arena_players(match_id,owner_id,nickname,seat,persona)
      select v_match,q.owner_id,q.nickname,row_number() over(order by random())::integer,q.persona
      from public.lbc_arena_queue q
      where q.owner_id=any(v_ids);
    end if;
  end if;

  select q.match_id,q.status into out_match_id,out_status
  from public.lbc_arena_queue q where q.owner_id=v_uid;

  select count(*)::integer into out_waiting
  from public.lbc_arena_queue
  where status='queued' and max_number=p_max_number and rounds=p_rounds and player_count=p_player_count;

  return next;
end;
$$;
revoke all on function public.lbc_arena_join_queue(text,integer,integer,integer,text) from public;
grant execute on function public.lbc_arena_join_queue(text,integer,integer,integer,text) to authenticated;

-- Helper repeated in complete/timeout: determine the next seat/round.
create or replace function public.lbc_arena_complete_turn(
  p_match_id uuid,
  p_round_number integer,
  p_round_score integer
)
returns table(out_status text,out_current_seat integer,out_current_round integer)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  m public.lbc_arena_matches%rowtype;
  p public.lbc_arena_players%rowtype;
  v_score integer;
  v_total integer;
  v_next integer;
  v_next_round integer;
begin
  if v_uid is null then raise exception 'not_authenticated'; end if;
  select * into m from public.lbc_arena_matches where id=p_match_id for update;
  if not found then raise exception 'match_not_found'; end if;
  select * into p from public.lbc_arena_players where match_id=p_match_id and owner_id=v_uid;
  if not found then raise exception 'not_match_member'; end if;

  if m.status<>'playing' or p.seat<>m.current_seat or p_round_number<>m.current_round then
    return query select m.status,m.current_seat,m.current_round; return;
  end if;

  v_score:=greatest(0,least(coalesce(p_round_score,0),999));
  select coalesce(sum(x),0)::integer into v_total from unnest(coalesce(p.round_scores,'{}'::integer[])) x;
  v_total:=v_total+v_score;

  update public.lbc_arena_players set
    round_scores=array_append(coalesce(round_scores,'{}'::integer[]),v_score),
    partial_score=v_total,
    total_score=case when m.current_round>=m.rounds then v_total else null end,
    status=case when m.current_round>=m.rounds then 'finished' else status end,
    last_seen=now(),updated_at=now()
  where match_id=p_match_id and owner_id=v_uid;

  select min(seat) into v_next from public.lbc_arena_players
  where match_id=p_match_id and status<>'abandoned' and seat>m.current_seat
    and coalesce(array_length(round_scores,1),0)<m.current_round;

  if v_next is not null then
    update public.lbc_arena_matches set current_seat=v_next,turn_started_at=now() where id=p_match_id;
  elsif m.current_round>=m.rounds then
    update public.lbc_arena_matches set status='finished',finished_at=now(),turn_started_at=null where id=p_match_id;
  else
    v_next_round:=m.current_round+1;
    select min(seat) into v_next from public.lbc_arena_players
    where match_id=p_match_id and status<>'abandoned'
      and coalesce(array_length(round_scores,1),0)<v_next_round;
    if v_next is null then
      update public.lbc_arena_matches set status='finished',finished_at=now(),turn_started_at=null where id=p_match_id;
    else
      update public.lbc_arena_matches set current_round=v_next_round,current_seat=v_next,turn_started_at=now() where id=p_match_id;
    end if;
  end if;

  return query select status,current_seat,current_round from public.lbc_arena_matches where id=p_match_id;
end;
$$;
revoke all on function public.lbc_arena_complete_turn(uuid,integer,integer) from public;
grant execute on function public.lbc_arena_complete_turn(uuid,integer,integer) to authenticated;

-- Any participant may advance a turn AFTER the server-side deadline.
-- This prevents everybody waiting forever if the active player puts the phone away.
create or replace function public.lbc_arena_force_timeout(p_match_id uuid)
returns table(out_status text,out_current_seat integer,out_current_round integer)
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  m public.lbc_arena_matches%rowtype;
  p public.lbc_arena_players%rowtype;
  st public.lbc_arena_state%rowtype;
  v_owner uuid;
  v_score integer;
  v_total integer;
  v_next integer;
  v_next_round integer;
begin
  if v_uid is null or not public.lbc_is_match_member(p_match_id) then raise exception 'not_match_member'; end if;
  select * into m from public.lbc_arena_matches where id=p_match_id for update;
  if not found then raise exception 'match_not_found'; end if;

  if m.status<>'playing' then return query select m.status,m.current_seat,m.current_round;return;end if;
  if m.turn_started_at is null or now() < m.turn_started_at + make_interval(secs=>m.turn_seconds) then
    return query select m.status,m.current_seat,m.current_round;return;
  end if;

  select owner_id into v_owner from public.lbc_arena_players where match_id=p_match_id and seat=m.current_seat;
  select * into p from public.lbc_arena_players where match_id=p_match_id and owner_id=v_owner;
  select * into st from public.lbc_arena_state
  where match_id=p_match_id and owner_id=v_owner and round_number=m.current_round;

  if found then
    v_score:=greatest(0,least(coalesce(st.round_score,0),999));
  else
    v_score:=(m.max_number*(m.max_number+1))/2;
  end if;

  select coalesce(sum(x),0)::integer into v_total from unnest(coalesce(p.round_scores,'{}'::integer[])) x;
  v_total:=v_total+v_score;

  update public.lbc_arena_players set
    round_scores=array_append(coalesce(round_scores,'{}'::integer[]),v_score),
    partial_score=v_total,
    total_score=case when m.current_round>=m.rounds then v_total else null end,
    status=case when status='abandoned' then 'abandoned'
                when m.current_round>=m.rounds then 'finished' else status end,
    updated_at=now()
  where match_id=p_match_id and owner_id=v_owner;

  select min(seat) into v_next from public.lbc_arena_players
  where match_id=p_match_id and status<>'abandoned' and seat>m.current_seat
    and coalesce(array_length(round_scores,1),0)<m.current_round;

  if v_next is not null then
    update public.lbc_arena_matches set current_seat=v_next,turn_started_at=now() where id=p_match_id;
  elsif m.current_round>=m.rounds then
    update public.lbc_arena_matches set status='finished',finished_at=now(),turn_started_at=null where id=p_match_id;
  else
    v_next_round:=m.current_round+1;
    select min(seat) into v_next from public.lbc_arena_players
    where match_id=p_match_id and status<>'abandoned'
      and coalesce(array_length(round_scores,1),0)<v_next_round;
    if v_next is null then
      update public.lbc_arena_matches set status='finished',finished_at=now(),turn_started_at=null where id=p_match_id;
    else
      update public.lbc_arena_matches set current_round=v_next_round,current_seat=v_next,turn_started_at=now() where id=p_match_id;
    end if;
  end if;

  return query select status,current_seat,current_round from public.lbc_arena_matches where id=p_match_id;
end;
$$;
revoke all on function public.lbc_arena_force_timeout(uuid) from public;
grant execute on function public.lbc_arena_force_timeout(uuid) to authenticated;

create or replace function public.lbc_arena_leave_match(p_match_id uuid)
returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_uid uuid:=auth.uid();
  m public.lbc_arena_matches%rowtype;
  p public.lbc_arena_players%rowtype;
begin
  if v_uid is null then return;end if;
  select * into m from public.lbc_arena_matches where id=p_match_id for update;
  select * into p from public.lbc_arena_players where match_id=p_match_id and owner_id=v_uid;
  if not found then return;end if;
  update public.lbc_arena_players set status='abandoned',updated_at=now() where match_id=p_match_id and owner_id=v_uid;
  if m.status='playing' and m.current_seat=p.seat then
    update public.lbc_arena_matches
      set turn_started_at=now()-make_interval(secs=>turn_seconds+1)
      where id=p_match_id;
  end if;
end;
$$;
revoke all on function public.lbc_arena_leave_match(uuid) from public;
grant execute on function public.lbc_arena_leave_match(uuid) to authenticated;

-- ---------- Realtime ----------
-- Safe to rerun: duplicate_object is ignored.
do $$
begin
  begin alter publication supabase_realtime add table public.lbc_arena_matches; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.lbc_arena_players; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.lbc_arena_state; exception when duplicate_object then null; end;
end $$;

-- Owner/admin can approve Community Voice entries manually in Table Editor for this beta:
-- update public.lbc_community_comments set status='approved',reviewed_at=now() where id=123;
